# Generated by Django 4.0.2 on 2022-07-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=4)),
                ('month', models.CharField(max_length=10)),
                ('variant', models.CharField(max_length=50)),
                ('questionNum', models.IntegerField(max_length=3)),
                ('answer', models.CharField(max_length=1)),
                ('hardness', models.IntegerField(max_length=5)),
                ('difficulty', models.IntegerField(max_length=5)),
            ],
        ),
    ]
