# Generated by Django 4.0.2 on 2022-07-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpaper',
            name='numberOfQuestion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='difficulty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='hardness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='questionNum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='year',
            field=models.IntegerField(),
        ),
    ]
